const Types = {
  START_REQUEST_PENDUDUK_MASUK: "START_REQUEST_PENDUDUK_MASUK",
  FETCH_KK_PENDUDUK_MASUK: "FETCH_KK_PENDUDUK_MASUK",
  POST_PENDUDUK_MASUK_SUCCESS: "POST_PENDUDUK_MASUK_SUCCESS",
  POST_KET_PENDUDUK_MASUK_SUCCESS: "POST_KET_PENDUDUK_MASUK_SUCCESS",
  PUT_PENDUDUK_MASUK_SUCCESS: "PUT_PENDUDUK_MASUK_SUCCESS",
  PUT_KETERANGAN_MASUK_SUCCESS: "PUT_KETERANGAN_MASUK_SUCCESS",
  DELETE_PENDUDUK_MASUK_SUCCESS: "DELETE_PENDUDUK_MASUK_SUCCESS",
  DELETE_KETERANGAN_MASUK_SUCCESS: "DELETE_KETERANGAN_MASUK_SUCCESS",
  FETCH_PENDUDUK_MASUK_SUCCESS_BY_ID: "FETCH_PENDUDUK_MASUK_SUCCESS_BY_ID",
  POST_ANGGOTA_PENDUDUK_MASUK_SUCCESS: "POST_ANGGOTA_PENDUDUK_MASUK_SUCCESS",
  FETCH_ANGGOTA_PENDUDUK_MASUK_SUCCESS_BY_ID:
    "FETCH_ANGGOTA_PENDUDUK_MASUK_SUCCESS_BY_ID",
  PUT_ANGGOTA_PENDUDUK_MASUK_SUCCESS_BY_ID:
    "PUT_ANGGOTA_PENDUDUK_MASUK_SUCCESS_BY_ID",
  SET_LOADING_PENDUDUK_MASUK_TO_FALSE: "SET_LOADING_PENDUDUK_MASUK_TO_FALSE",
};

export default Types;
