const Types = {
  START_REQUEST: "START_REQUEST",
  FETCH_KETERANGAN_PENGIKUT_KELUAR_SUCCESS:
    "FETCH_KETERANGAN_PENGIKUT_KELUAR_SUCCESS",
  POST_KETERANGAN_KELUAR_SUCCESS: "POST_KETERANGAN_KELUAR_SUCCESS",
  POST_PENGIKUT_KELUAR_SUCCESS: "POST_PENGIKUT_KELUAR_SUCCESS",
  PUT_KETERANGAN_KELUAR_SUCCESS: "PUT_KETERANGAN_KELUAR_SUCCESS",
  PUT_PENGIKUT_KELUAR_SUCCESS: "PUT_PENGIKUT_KELUAR_SUCCESS",
  DELETE_KETERANGAN_KELUAR_SUCCESS: "DELETE_KETERANGAN_KELUAR_SUCCESS",
  DELETE_PENGIKUT_KELUAR_SUCCESS: "DELETE_PENGIKUT_KELUAR_SUCCESS",
};

export default Types;
