const Types = {
  START_REQUEST_ANGGOTA_KELUARGA: "START_REQUEST_ANGGOTA_KELUARGA",
  POST_ANGGOTA_KELUARGA_SUCCESS: "POST_ANGGOTA_KELUARGA_SUCCESS",
  PUT_ANGGOTA_KELUARGA_SUCCESS: "PUT_ANGGOTA_KELUARGA_SUCCESS",
  DELETE_ANGGOTA_KELUARGA_SUCCESS: "DELETE_ANGGOTA_KELUARGA_SUCCESS",
  FETCH_ANGGOTA_KELUARGA_SUCCESS_BY_ID: "FETCH_ANGGOTA_KELUARGA_SUCCESS_BY_ID",
  SET_LOADING_TO_FALSE_INSERT_KELUARGA: "SET_LOADING_TO_FALSE_INSERT_KELUARGA",
};

export default Types;
