const Types = {
  START_REQUEST_KEMATIAN: "START_REQUEST_KEMATIAN",
  FETCH_KEMATIAN_SUCCESS: "FETCH_KEMATIAN_SUCCESS",
  FETCH_KEMATIAN_BY_ID_SUCCESS: "FETCH_KEMATIAN_BY_ID_SUCCESS",
  POST_KEMATIAN_SUCCESS: "POST_KEMATIAN_SUCCESS",
  POST_ARSIP_KEMATIAN_SUCCESS: "POST_ARSIP_KEMATIAN_SUCCESS",
  PUT_ARSIP_KEMATIAN_SUCCESS: "PUT_ARSIP_KEMATIAN_SUCCESS",
  DELETE_ARSIP_KEMATIAN_SUCCESS: "DELETE_ARSIP_KEMATIAN_SUCCESS",
  PUT_KEMATIAN_SUCCESS: "PUT_KEMATIAN_SUCCESS",
  DELETE_KEMATIAN_SUCCESS: "DELETE_KEMATIAN_SUCCESS",
};

export default Types;
