const Types = {
  START_REQUEST_KELAHIRAN: "START_REQUEST_KELAHIRAN",
  FETCH_KELAHIRAN_SUCCESS: "FETCH_KELAHIRAN_SUCCESS",
  FETCH_KELAHIRAN_BY_ID_SUCCESS: "FETCH_KELAHIRAN_BY_ID_SUCCESS",
  POST_KELAHIRAN_SUCCESS: "POST_KELAHIRAN_SUCCESS",
  PUT_KELAHIRAN_SUCCESS: "PUT_KELAHIRAN_SUCCESS",
  DELETE_KELAHIRAN_SUCCESS: "DELETE_KELAHIRAN_SUCCESS",
  SET_LOADING_TO_FALSE_KELAHIRAN: "SET_LOADING_TO_FALSE_KELAHIRAN",
};

export default Types;
