const Types = {
  START_REQUEST: "START_REQUEST",
  FETCH_PENDUDUK_SUCCESS: "FETCH_PENDUDUK_SUCCESS",
  POST_PENDUDUK_SUCCESS: "POST_PENDUDUK_SUCCESS",
  PUT_PENDUDUK_SUCCESS: "PUT_PENDUDUK_SUCCESS",
  DELETE_PENDUDUK_SUCCESS: "DELETE_PENDUDUK_SUCCESS",
};

export default Types;
