const Types = {
  START_REQUEST_PENDUDUK: "START_REQUEST_PENDUDUK",
  FETCH_PENDUDUK_SUCCESS: "FETCH_PENDUDUK_SUCCESS",
  FETCH_PENDUDUK_SUCCESS_BY_ID: "FETCH_PENDUDUK_SUCCESS_BY_ID",
  SEARCH_PENDUDUK_BY_NAME: "SEARCH_PENDUDUK_BY_NAME",
  SEARCH_PENDUDUK_BY_NO_NIK: "SEARCH_PENDUDUK_BY_NO_NIK",
  SEARCH_PENDUDUK_BY_NO_KK: "SEARCH_PENDUDUK_BY_NO_KK",
  CLEAR_SEARCH_PENDUDUK_RESULT: "CLEAR_SEARCH_PENDUDUK_RESULT",
  SET_LOADING_PENDUDUK_TO_FALSE: "SET_LOADING_PENDUDUK_TO_FALSE",
};

export default Types;
