const Types = {
  START_REQUEST_PENDUDUK: "START_REQUEST_PENDUDUK",
  FETCH_PENDUDUK_SUCCESS: "FETCH_PENDUDUK_SUCCESS",
  FETCH_PENDUDUK_SUCCESS_BY_ID: "FETCH_PENDUDUK_SUCCESS_BY_ID",
};

export default Types;
