const Types = {
  START_REQUEST_ADMIN_ACTIVITY: "START_REQUEST_ADMIN_ACTIVITY",
  GET_ADMIN_ACTIVITY: "GET_ADMIN_ACTIVITY",
  POST_ADMIN_LOGOUT_ACTIVITY: "POST_ADMIN_LOGOUT_ACTIVITY",
};

export default Types;
