const Types = {
  START_REQUEST_KELUAR: "START_REQUEST_KELUAR",
  FETCH_PENDUDUK_KELUAR_SUCCESS: "FETCH_PENDUDUK_KELUAR_SUCCESS",
  FETCH_KETERANGAN_KELUAR_SUCCESS: "FETCH_KETERANGAN_KELUAR_SUCCESS",
  PUT_KETERANGAN_KELUAR_SUCCESS: "PUT_KETERANGAN_KELUAR_SUCCESS",
  DELETE_KETERANGAN_KELUAR_SUCCESS: "DELETE_KETERANGAN_KELUAR_SUCCESS",
  PUT_PENDUDUK_KELUAR_SUCCESS: "PUT_PENDUDUK_KELUAR_SUCCESS",
  DELETE_PENDUDUK_KELUAR_SUCCESS: "DELETE_PENDUDUK_KELUAR_SUCCESS",
  FETCH_PENDUDUK_KELUAR_SUCCESS_BY_ID: "FETCH_PENDUDUK_KELUAR_SUCCESS_BY_ID",
};

export default Types;
