const Types = {
  START_REQUEST_KELUAR: "START_REQUEST_KELUAR",
  FETCH_PENDUDUK_KELUAR_SUCCESS: "FETCH_PENDUDUK_KELUAR_SUCCESS",
  FETCH_KETERANGAN_KELUAR_DETAIL_SUCCESS:
    "FETCH_KETERANGAN_KELUAR_DETAIL_SUCCESS",
  FETCH_PENGIKUT_KELUAR_DETAILS: "FETCH_PENGIKUT_KELUAR_DETAILS",
  PUT_KETERANGAN_KELUAR_SUCCESS: "PUT_KETERANGAN_KELUAR_SUCCESS",
  DELETE_KETERANGAN_KELUAR_SUCCESS: "DELETE_KETERANGAN_KELUAR_SUCCESS",
  PUT_PENGIKUT_KELUAR_SUCCESS: "PUT_PENGIKUT_KELUAR_SUCCESS",
  DELETE_PENGIKUT_KELUAR_SUCCESS: "DELETE_PENGIKUT_KELUAR_SUCCESS",
  FETCH_PENDUDUK_KELUAR_SUCCESS_BY_ID: "FETCH_PENDUDUK_KELUAR_SUCCESS_BY_ID",
};

export default Types;
