const Types = {
  START_REQUEST_PENDUDUK_KELUAR: "START_REQUEST_PENDUDUK_KELUAR",
  FETCH_PENDUDUK_KELUAR_SUCCESS: "FETCH_PENDUDUK_KELUAR_SUCCESS",
  POST_PENDUDUK_KELUAR_SUCCESS: "POST_PENDUDUK_KELUAR_SUCCESS",
  POST_MANY_PENDUDUK_KELUAR_SUCCESS: "POST_MANY_PENDUDUK_KELUAR_SUCCESS",
  POST_KETERANGAN_KELUAR_SUCCESS: "POST_KETERANGAN_KELUAR_SUCCESS",
  DELETE_PENDUDUK_KELUAR_SUCCESS: "DELETE_PENDUDUK_KELUAR_SUCCESS",
  DELETE_ALL_DATA_PENDUDUK_KELUAR_SUCCESS:
    "DELETE_ALL_DATA_PENDUDUK_KELUAR_SUCCESS",
  FETCH_PENDUDUK_KELUAR_SUCCESS_BY_ID: "FETCH_PENDUDUK_KELUAR_SUCCESS_BY_ID",
  SET_LOADING_TO_FALSE_PENDUDUK_KELUAR: "SET_LOADING_TO_FALSE_PENDUDUK_KELUAR",
  UPDATE_KETERANGAN_KELUAR_SUCCESS: "UPDATE_KETERANGAN_KELUAR_SUCCESS",
  DELETE_KETERANGAN_KELUAR_SUCCESS: "DELETE_KETERANGAN_KELUAR_SUCCESS",
};

export default Types;
