const Types = {
  START_REQUEST_SIGNATURES: "START_REQUEST_SIGNATURES",
  POST_SIGNATURES_SUCCESS: "POST_SIGNATURES_SUCCESS",
  PUT_SIGNATURES_SUCCESS: "PUT_SIGNATURES_SUCCESS",
};

export default Types;
