const Types = {
  START_REQUEST_KK: "START_REQUEST_KK",
  FETCH_KARTU_KELUARGA_SUCCESS: "FETCH_KARTU_KELUARGA_SUCCESS",
  POST_KARTU_KELUARGA_SUCCESS: "POST_KARTU_KELUARGA_SUCCESS",
  PUT_KARTU_KELUARGA_SUCCESS: "PUT_KARTU_KELUARGA_SUCCESS",
  DELETE_KARTU_KELUARGA_SUCCESS: "DELETE_KARTU_KELUARGA_SUCCESS",
  FETCH_KARTU_KELUARGA_SUCCESS_BY_ID: "FETCH_KARTU_KELUARGA_SUCCESS_BY_ID",
};

export default Types;
