const Types = {
  START_REQUEST_KK: "START_REQUEST_KK",
  FETCH_KARTU_KELUARGA_SUCCESS: "FETCH_KARTU_KELUARGA_SUCCESS",
  POST_KARTU_KELUARGA_SUCCESS: "POST_KARTU_KELUARGA_SUCCESS",
  PUT_KARTU_KELUARGA_SUCCESS: "PUT_KARTU_KELUARGA_SUCCESS",
  DELETE_KARTU_KELUARGA_SUCCESS: "DELETE_KARTU_KELUARGA_SUCCESS",
  FETCH_KARTU_KELUARGA_SUCCESS_BY_ID: "FETCH_KARTU_KELUARGA_SUCCESS_BY_ID",
  SEARCH_KK_BY_NAME: "SEARCH_KK_BY_NAME",
  SEARCH_KK_NO_NIK: "SEARCH_KK_NO_NIK",
  CLEAR_SEARCH_RESULT: "CLEAR_SEARCH_RESULT",
};

export default Types;
